// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *FooterMenu → linksGroup*
 */
export interface FootermenuDocumentDataLinksgroupItem {
  /**
   * linkstem field in *FooterMenu → linksGroup*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.linksgroup[].linkitem
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkitem: prismic.LinkField;

  /**
   * linkLabel field in *FooterMenu → linksGroup*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.linksgroup[].linklabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel: prismic.KeyTextField;
}

/**
 * Item in *FooterMenu → socialMediaGroup*
 */
export interface FootermenuDocumentDataSocialmediasItem {
  /**
   * socialMediaLabel field in *FooterMenu → socialMediaGroup*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.socialmedias[].socialmedialabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  socialmedialabel: prismic.KeyTextField;

  /**
   * socialMediaLink field in *FooterMenu → socialMediaGroup*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.socialmedias[].socialmediaLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  socialmediaLink: prismic.LinkField;

  /**
   * socialMediaIcon field in *FooterMenu → socialMediaGroup*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.socialmedias[].socialmediaicon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  socialmediaicon: prismic.ImageField<never>;
}

/**
 * Content for FooterMenu documents
 */
interface FootermenuDocumentData {
  /**
   * linksGroup field in *FooterMenu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.linksgroup[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  linksgroup: prismic.GroupField<
    Simplify<FootermenuDocumentDataLinksgroupItem>
  >;

  /**
   * copyright field in *FooterMenu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright: prismic.KeyTextField;

  /**
   * socialMediaGroup field in *FooterMenu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footermenu.socialmedias[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socialmedias: prismic.GroupField<
    Simplify<FootermenuDocumentDataSocialmediasItem>
  >;
}

/**
 * FooterMenu document from Prismic
 *
 * - **API ID**: `footermenu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FootermenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FootermenuDocumentData>,
    "footermenu",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | PhotoWithTextBlockSlice
  | PopOutTextSlice
  | HeroBannerWithTextSlice;

/**
 * Content for HomePage documents
 */
interface HomepageDocumentData {
  /**
   * navigationMenu field in *HomePage*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.navigationmenu
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navigationmenu: prismic.ContentRelationshipField<"navigationmenu">;

  /**
   * footerMenu field in *HomePage*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.footermenu
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  footermenu: prismic.ContentRelationshipField<"footermenu">;

  /**
   * Slice Zone field in *HomePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *HomePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type MultiphotosblockDocumentDataSlicesSlice = PhotoWithTextBlockSlice;

/**
 * Content for MultiPhotosBlock documents
 */
interface MultiphotosblockDocumentData {
  /**
   * Slice Zone field in *MultiPhotosBlock*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: multiphotosblock.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MultiphotosblockDocumentDataSlicesSlice>;
}

/**
 * MultiPhotosBlock document from Prismic
 *
 * - **API ID**: `multiphotosblock`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MultiphotosblockDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MultiphotosblockDocumentData>,
    "multiphotosblock",
    Lang
  >;

/**
 * Item in *NavigationMenu → navigationLink*
 */
export interface NavigationmenuDocumentDataNavigationlinkItem {
  /**
   * linkItem field in *NavigationMenu → navigationLink*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigationmenu.navigationlink[].linkitem
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkitem: prismic.LinkField;

  /**
   * linkLabel field in *NavigationMenu → navigationLink*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigationmenu.navigationlink[].linklabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linklabel: prismic.KeyTextField;
}

/**
 * Content for NavigationMenu documents
 */
interface NavigationmenuDocumentData {
  /**
   * navigationLink field in *NavigationMenu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigationmenu.navigationlink[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigationlink: prismic.GroupField<
    Simplify<NavigationmenuDocumentDataNavigationlinkItem>
  >;
}

/**
 * NavigationMenu document from Prismic
 *
 * - **API ID**: `navigationmenu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationmenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationmenuDocumentData>,
    "navigationmenu",
    Lang
  >;

type NavigationpageDocumentDataSlicesSlice =
  | HeroBannerWithTextSlice
  | PhotoWithTextBlockSlice
  | PopOutTextSlice;

/**
 * Content for NavigationPage documents
 */
interface NavigationpageDocumentData {
  /**
   * navigationMenu field in *NavigationPage*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: navigationpage.navigationmenu
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navigationmenu: prismic.ContentRelationshipField<"navigationmenu">;

  /**
   * footerMenu field in *NavigationPage*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: navigationpage.footermenu
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  footermenu: prismic.ContentRelationshipField<"footermenu">;

  /**
   * Slice Zone field in *NavigationPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigationpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavigationpageDocumentDataSlicesSlice> /**
   * Meta Title field in *NavigationPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: navigationpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *NavigationPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: navigationpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *NavigationPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigationpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * NavigationPage document from Prismic
 *
 * - **API ID**: `navigationpage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NavigationpageDocumentData>,
    "navigationpage",
    Lang
  >;

export type AllDocumentTypes =
  | FootermenuDocument
  | HomepageDocument
  | MultiphotosblockDocument
  | NavigationmenuDocument
  | NavigationpageDocument;

/**
 * Item in *HeroBannerWithText →  HeroBannerWithText-Buttons → Primary → buttonsGroups*
 */
export interface HeroBannerWithTextSliceHeroBannerWithTextButtonsPrimaryButtonsgroupsItem {
  /**
   * buttonLink field in *HeroBannerWithText →  HeroBannerWithText-Buttons → Primary → buttonsGroups*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner_with_text.heroBannerWithTextButtons.primary.buttonsgroups[].buttonitem
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonitem: prismic.LinkField;

  /**
   * buttonLabel field in *HeroBannerWithText →  HeroBannerWithText-Buttons → Primary → buttonsGroups*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner_with_text.heroBannerWithTextButtons.primary.buttonsgroups[].buttonlabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonlabel: prismic.KeyTextField;
}

/**
 * Primary content in *HeroBannerWithText → Default → Primary*
 */
export interface HeroBannerWithTextSliceDefaultPrimary {
  /**
   * heroImage field in *HeroBannerWithText → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner_with_text.default.primary.heroimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  heroimage: prismic.ImageField<never>;

  /**
   * heroImagePosition field in *HeroBannerWithText → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: right
   * - **API ID Path**: hero_banner_with_text.default.primary.heroimageposition
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  heroimageposition: prismic.SelectField<"right" | "left", "filled">;

  /**
   * subText field in *HeroBannerWithText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner_with_text.default.primary.subtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtext: prismic.RichTextField;

  /**
   * headingText field in *HeroBannerWithText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner_with_text.default.primary.headingtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headingtext: prismic.RichTextField;

  /**
   * descriptionParagraph field in *HeroBannerWithText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner_with_text.default.primary.descriptionparagraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descriptionparagraph: prismic.RichTextField;

  /**
   * variant field in *HeroBannerWithText → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: dark
   * - **API ID Path**: hero_banner_with_text.default.primary.variant
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  variant: prismic.SelectField<"dark" | "light", "filled">;
}

/**
 * Default variation for HeroBannerWithText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerWithTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroBannerWithTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeroBannerWithText →  HeroBannerWithText-Buttons → Primary*
 */
export interface HeroBannerWithTextSliceHeroBannerWithTextButtonsPrimary {
  /**
   * heroImage field in *HeroBannerWithText →  HeroBannerWithText-Buttons → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner_with_text.heroBannerWithTextButtons.primary.heroimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  heroimage: prismic.ImageField<never>;

  /**
   * heroImagePosition field in *HeroBannerWithText →  HeroBannerWithText-Buttons → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: right
   * - **API ID Path**: hero_banner_with_text.heroBannerWithTextButtons.primary.heroimageposition
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  heroimageposition: prismic.SelectField<"right" | "left", "filled">;

  /**
   * subText field in *HeroBannerWithText →  HeroBannerWithText-Buttons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner_with_text.heroBannerWithTextButtons.primary.subtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtext: prismic.RichTextField;

  /**
   * headingText field in *HeroBannerWithText →  HeroBannerWithText-Buttons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner_with_text.heroBannerWithTextButtons.primary.headingtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headingtext: prismic.RichTextField;

  /**
   * descriptionParagraph field in *HeroBannerWithText →  HeroBannerWithText-Buttons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner_with_text.heroBannerWithTextButtons.primary.descriptionparagraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descriptionparagraph: prismic.RichTextField;

  /**
   * variant field in *HeroBannerWithText →  HeroBannerWithText-Buttons → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: dark
   * - **API ID Path**: hero_banner_with_text.heroBannerWithTextButtons.primary.variant
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  variant: prismic.SelectField<"dark" | "light", "filled">;

  /**
   * buttonsGroups field in *HeroBannerWithText →  HeroBannerWithText-Buttons → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner_with_text.heroBannerWithTextButtons.primary.buttonsgroups[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  buttonsgroups: prismic.GroupField<
    Simplify<HeroBannerWithTextSliceHeroBannerWithTextButtonsPrimaryButtonsgroupsItem>
  >;
}

/**
 *  HeroBannerWithText-Buttons variation for HeroBannerWithText Slice
 *
 * - **API ID**: `heroBannerWithTextButtons`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerWithTextSliceHeroBannerWithTextButtons =
  prismic.SharedSliceVariation<
    "heroBannerWithTextButtons",
    Simplify<HeroBannerWithTextSliceHeroBannerWithTextButtonsPrimary>,
    never
  >;

/**
 * Slice variation for *HeroBannerWithText*
 */
type HeroBannerWithTextSliceVariation =
  | HeroBannerWithTextSliceDefault
  | HeroBannerWithTextSliceHeroBannerWithTextButtons;

/**
 * HeroBannerWithText Shared Slice
 *
 * - **API ID**: `hero_banner_with_text`
 * - **Description**: HeroBannerWithText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerWithTextSlice = prismic.SharedSlice<
  "hero_banner_with_text",
  HeroBannerWithTextSliceVariation
>;

/**
 * Primary content in *PhotoWithTextBlock → Default → Primary*
 */
export interface PhotoWithTextBlockSliceDefaultPrimary {
  /**
   * photo field in *PhotoWithTextBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: photo_with_text_block.default.primary.photo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo: prismic.ImageField<never>;

  /**
   * title field in *PhotoWithTextBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: photo_with_text_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *PhotoWithTextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: photo_with_text_block.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for PhotoWithTextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PhotoWithTextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PhotoWithTextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PhotoWithTextBlock*
 */
type PhotoWithTextBlockSliceVariation = PhotoWithTextBlockSliceDefault;

/**
 * PhotoWithTextBlock Shared Slice
 *
 * - **API ID**: `photo_with_text_block`
 * - **Description**: PhotoWithTextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PhotoWithTextBlockSlice = prismic.SharedSlice<
  "photo_with_text_block",
  PhotoWithTextBlockSliceVariation
>;

/**
 * Primary content in *PopOutText → Default → Primary*
 */
export interface PopOutTextSliceDefaultPrimary {
  /**
   * text field in *PopOutText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_out_text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for PopOutText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopOutTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PopOutTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PopOutText*
 */
type PopOutTextSliceVariation = PopOutTextSliceDefault;

/**
 * PopOutText Shared Slice
 *
 * - **API ID**: `pop_out_text`
 * - **Description**: PopOutText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopOutTextSlice = prismic.SharedSlice<
  "pop_out_text",
  PopOutTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FootermenuDocument,
      FootermenuDocumentData,
      FootermenuDocumentDataLinksgroupItem,
      FootermenuDocumentDataSocialmediasItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      MultiphotosblockDocument,
      MultiphotosblockDocumentData,
      MultiphotosblockDocumentDataSlicesSlice,
      NavigationmenuDocument,
      NavigationmenuDocumentData,
      NavigationmenuDocumentDataNavigationlinkItem,
      NavigationpageDocument,
      NavigationpageDocumentData,
      NavigationpageDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeroBannerWithTextSlice,
      HeroBannerWithTextSliceDefaultPrimary,
      HeroBannerWithTextSliceHeroBannerWithTextButtonsPrimaryButtonsgroupsItem,
      HeroBannerWithTextSliceHeroBannerWithTextButtonsPrimary,
      HeroBannerWithTextSliceVariation,
      HeroBannerWithTextSliceDefault,
      HeroBannerWithTextSliceHeroBannerWithTextButtons,
      PhotoWithTextBlockSlice,
      PhotoWithTextBlockSliceDefaultPrimary,
      PhotoWithTextBlockSliceVariation,
      PhotoWithTextBlockSliceDefault,
      PopOutTextSlice,
      PopOutTextSliceDefaultPrimary,
      PopOutTextSliceVariation,
      PopOutTextSliceDefault,
    };
  }
}
