<!-- https://uiverse.io/alexruix/tame-fly-42 -->

<template>
  <div
    class="page-loader"
    :class="{ 'fade-out-fwd': !show, 'full-censored': fullCensored }"
  >
    <div class="loader"></div>
  </div>
</template>

<script setup lang="ts">
const props = withDefaults(
  defineProps<{
    show: boolean;
    fullCensored?: boolean;
  }>(),
  {
    fullCensored: false,
  }
);
</script>

<style lang="css">
.page-loader {
  position: fixed !important;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: rgba(0, 0, 0, 0.9);
  backdrop-filter: blur(7.2px) brightness(1.2);
  width: 100dvw;
  height: 100svh;
  overflow: hidden;
  top: 0;
  left: 0;
  z-index: 999;
}

/* .page-loader:is(.fade-out-fwd) {
  pointer-events: none;
} */

.page-loader:is(.full-censored) {
  background-color: black;
}

/* HTML: <div class="loader"></div> */
.loader {
  width: 64px;
  aspect-ratio: 1;
  --_g: no-repeat url("/img/sprite-cat.png");
  background:
    var(--_g) 0 0,
    var(--_g) 100% 0,
    var(--_g) 100% 100%,
    var(--_g) 0 100%;
  background-size: 40% 40%;
  animation: l38 0.72s infinite;
}

@keyframes l38 {
  100% {
    background-position:
      100% 0,
      100% 100%,
      0 100%,
      0 0;
  }
}

.slide-out-bottom {
  -webkit-animation: slide-out-bottom 0.72s
    cubic-bezier(0.55, 0.085, 0.68, 0.53) 1.4s both;
  animation: slide-out-bottom 0.72s cubic-bezier(0.55, 0.085, 0.68, 0.53) 1.4s
    both;
}

.fade-out-fwd {
  -webkit-animation: fade-out-fwd 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: fade-out-fwd 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

@keyframes loading-bounce {
  0% {
    transform: scale(1, 0.7);
  }

  40% {
    transform: scale(0.8, 1.2);
  }

  60% {
    transform: scale(1, 1);
  }

  100% {
    bottom: 140px;
  }
}

@keyframes loading-step {
  0% {
    box-shadow:
      0 10px 0 rgba(0, 0, 0, 0),
      0 10px 0 #f2f2f2,
      -35px 50px 0 #f2f2f2,
      -70px 90px 0 #f2f2f2;
  }

  100% {
    box-shadow:
      0 10px 0 #f2f2f2,
      -35px 50px 0 #f2f2f2,
      -70px 90px 0 #f2f2f2,
      -70px 90px 0 rgba(0, 0, 0, 0);
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2024-9-25 10:54:34
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-out-bottom
 * ----------------------------------------
 */
@-webkit-keyframes slide-out-bottom {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateY(1000px);
    transform: translateY(1000px);
    opacity: 0;
  }
}
@keyframes slide-out-bottom {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateY(1000px);
    transform: translateY(1000px);
    opacity: 0;
  }
}
/* ----------------------------------------------
 * Generated by Animista on 2024-10-17 12:21:10
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-out-fwd
 * ----------------------------------------
 */
@-webkit-keyframes fade-out-fwd {
  0% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateZ(80px);
    transform: translateZ(80px);
    opacity: 0;
  }
}
@keyframes fade-out-fwd {
  0% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateZ(80px);
    transform: translateZ(80px);
    opacity: 0;
  }
}
</style>
