<!-- https://uiverse.io/alexruix/tame-fly-42 -->

<template>
  <div class="page-loader slit-out-horizontal">
    <div class="loader"></div>
  </div>
</template>

<style lang="css">
.page-loader {
  position: fixed !important;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: var(--gray-dark);
  width: 100dvw;
  height: 100svh;
  overflow: hidden;
  top: 0;
  left: 0;
  z-index: 999;
}

.loader {
  position: relative;
  width: 120px;
  height: 90px;
  margin: 0 auto;
}

.loader:before {
  content: "";
  position: absolute;
  bottom: 30px;
  left: 50px;
  height: 30px;
  width: 30px;
  border-radius: 50%;
  background-image: url("/img/sprite-cat.png");
  background-position: center;
  background-size: contain;
  background-repeat: no-repeat;
  animation: loading-bounce 0.5s ease-in-out infinite alternate;
}

.loader:after {
  content: "";
  position: absolute;
  right: 0;
  top: 0;
  height: 7px;
  width: 45px;
  border-radius: 4px;
  box-shadow:
    0 5px 0 #f2f2f2,
    -35px 50px 0 #f2f2f2,
    -70px 95px 0 #f2f2f2;
  animation: loading-step 1s ease-in-out infinite;
}

.roll-out-blurred-left {
  -webkit-animation: roll-out-blurred-left 0.65s
    cubic-bezier(0.755, 0.05, 0.855, 0.06) 1.4s both;
  animation: roll-out-blurred-left 0.65s cubic-bezier(0.755, 0.05, 0.855, 0.06)
    1.4s both;
}

.slit-out-horizontal {
	-webkit-animation: slit-out-horizontal 0.72s ease-in 1.4s both;
	        animation: slit-out-horizontal 0.72s ease-in 1.4s both;
}

@keyframes loading-bounce {
  0% {
    transform: scale(1, 0.7);
  }

  40% {
    transform: scale(0.8, 1.2);
  }

  60% {
    transform: scale(1, 1);
  }

  100% {
    bottom: 140px;
  }
}

@keyframes loading-step {
  0% {
    box-shadow:
      0 10px 0 rgba(0, 0, 0, 0),
      0 10px 0 #f2f2f2,
      -35px 50px 0 #f2f2f2,
      -70px 90px 0 #f2f2f2;
  }

  100% {
    box-shadow:
      0 10px 0 #f2f2f2,
      -35px 50px 0 #f2f2f2,
      -70px 90px 0 #f2f2f2,
      -70px 90px 0 rgba(0, 0, 0, 0);
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2024-9-25 0:50:59
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation roll-out-blurred-left
 * ----------------------------------------
 */
@-webkit-keyframes roll-out-blurred-left {
  0% {
    -webkit-transform: translateX(0) rotate(0deg);
    transform: translateX(0) rotate(0deg);
    -webkit-filter: blur(0);
    filter: blur(0);
    opacity: 1;
    border-radius: 0;
  }
  100% {
    -webkit-transform: translateX(-1000px) rotate(-720deg);
    transform: translateX(-1000px) rotate(-720deg);
    -webkit-filter: blur(50px);
    filter: blur(50px);
    opacity: 0;
    border-radius: 120vw;
    background-color: var(--black);
  }
}
@keyframes roll-out-blurred-left {
  0% {
    -webkit-transform: translateX(0) rotate(0deg);
    transform: translateX(0) rotate(0deg);
    -webkit-filter: blur(0);
    filter: blur(0);
    opacity: 1;
    border-radius: 0;
  }
  100% {
    -webkit-transform: translateX(-1000px) rotate(-720deg);
    transform: translateX(-1000px) rotate(-720deg);
    -webkit-filter: blur(50px);
    filter: blur(50px);
    opacity: 0;
    border-radius: 120vw;
    background-color: var(--black);
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2024-9-25 10:45:46
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slit-out-horizontal
 * ----------------------------------------
 */
@-webkit-keyframes slit-out-horizontal {
  0% {
    -webkit-transform: translateZ(0) rotateX(0);
            transform: translateZ(0) rotateX(0);
    opacity: 1;
  }
  54% {
    -webkit-transform: translateZ(-160px) rotateX(87deg);
            transform: translateZ(-160px) rotateX(87deg);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateZ(-800px) rotateX(90deg);
            transform: translateZ(-800px) rotateX(90deg);
    opacity: 0;
  }
}
@keyframes slit-out-horizontal {
  0% {
    -webkit-transform: translateZ(0) rotateX(0);
            transform: translateZ(0) rotateX(0);
    opacity: 1;
  }
  54% {
    -webkit-transform: translateZ(-160px) rotateX(87deg);
            transform: translateZ(-160px) rotateX(87deg);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateZ(-800px) rotateX(90deg);
            transform: translateZ(-800px) rotateX(90deg);
    opacity: 0;
  }
}

</style>
