// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  adoptions_group: defineAsyncComponent(
    () => import("./AdoptionsGroup/index.vue"),
  ),
  hero_banner_with_text: defineAsyncComponent(
    () => import("./HeroBannerWithText/index.vue"),
  ),
  hero_photo_background: defineAsyncComponent(
    () => import("./HeroPhotoBackground/index.vue"),
  ),
  map_with_text_block: defineAsyncComponent(
    () => import("./MapWithTextBlock/index.vue"),
  ),
  multi_text_block: defineAsyncComponent(
    () => import("./MultiTextBlock/index.vue"),
  ),
  photo_with_text_block: defineAsyncComponent(
    () => import("./PhotoWithTextBlock/index.vue"),
  ),
  pop_out_text: defineAsyncComponent(() => import("./PopOutText/index.vue")),
});
