// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  hero_banner_with_text: defineAsyncComponent(
    () => import("./HeroBannerWithText/index.vue"),
  ),
  photo_with_text_block: defineAsyncComponent(
    () => import("./PhotoWithTextBlock/index.vue"),
  ),
  pop_out_text: defineAsyncComponent(() => import("./PopOutText/index.vue")),
});
